package br.com.soaexpert.empresaservice;

import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.Holder;
import br.com.soaexpert.domain.Credito;
import br.com.soaexpert.domain.Empresa;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.5 Generated
 * source version: 2.1
 * 
 */
@WebService(portName = "EmpresaServiceSOAP", serviceName = "EmpresaService", targetNamespace = "http://www.soaexpert.com.br/EmpresaService/", wsdlLocation = "/wsdls/EmpresaService.wsdl", endpointInterface = "br.com.soaexpert.empresaservice.EmpresaService")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class EmpresaService_EmpresaServiceSOAPImpl implements EmpresaService {

	public EmpresaService_EmpresaServiceSOAPImpl() {
	}

	/**
	 * 
	 * @param empresa
	 * @return returns boolean
	 */
	public boolean verificaCadastro(Empresa empresa) {
		// replace with your impl here
		return false;
	}

	/**
	 * 
	 * @param empresa
	 * @return returns br.com.soaexpert.domain.Credito
	 */
	public Credito verificaCredito(Empresa empresa) {
		// replace with your impl here
		return null;
	}

	/**
	 * 
	 * @param empresa
	 */
	public void rejeita(Empresa empresa) {
		// replace with your impl here
		return;
	}

	/**
	 * 
	 * @param empresa
	 */
	public void aprovaEmpresa(Empresa empresa) {
		// replace with your impl here
		return;
	}

	/**
	 * 
	 * @param empresa
	 */
	public void cadastra(Holder<Empresa> empresa) {
		// replace with your impl here
		return;
	}

}
