package br.com.soaexpert.creditoservice;

import javax.jws.WebService;
import javax.xml.ws.BindingType;
import br.com.soaexpert.domain.Credito;
import br.com.soaexpert.domain.Empresa;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.5 Generated
 * source version: 2.1
 * 
 */
@WebService(portName = "CreditoServiceSOAP", serviceName = "CreditoService", targetNamespace = "http://www.soaexpert.com.br/CreditoService/", wsdlLocation = "/wsdls/CreditoService.wsdl", endpointInterface = "br.com.soaexpert.creditoservice.CreditoService")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class CreditoService_CreditoServiceSOAPImpl implements CreditoService {

	/**
	 * 
	 * @param empresa
	 * @return returns br.com.soaexpert.domain.Credito
	 */
	public Credito vefiricaCreditoSerasa(Empresa empresa) {
		Credito credito = new Credito();
		credito.setEmpresa(empresa);
		credito.setSerasa(true);
		credito.setAprovado(false);
		return credito;
	}

	/**
	 * 
	 * @param empresa
	 * @return returns br.com.soaexpert.domain.Credito
	 */
	public Credito verificaCreditoSPC(Empresa empresa) {
		Credito credito = new Credito();
		credito.setEmpresa(empresa);
		credito.setSpc(true);
		credito.setAprovado(false);
		return credito;
	}

	/**
	 * 
	 * @param empresa
	 * @return returns br.com.soaexpert.domain.Credito
	 */
	public Credito verificaCasasBahia(Empresa empresa) {
		Credito credito = new Credito();
		credito.setEmpresa(empresa);
		credito.setCasasBahia(true);
		credito.setAprovado(false);
		return credito;
	}

}
