package br.com.soaexpert.creditoservice;

import java.util.HashSet;
import java.util.Set;

import javax.jws.WebService;
import javax.xml.ws.BindingType;

import br.com.soaexpert.domain.Credito;
import br.com.soaexpert.domain.Empresa;

import com.certicom.ecc.util.Random;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.5 Generated
 * source version: 2.1
 * 
 */
@WebService(portName = "CreditoServiceSOAP", serviceName = "CreditoService", targetNamespace = "http://www.soaexpert.com.br/CreditoService/", wsdlLocation = "/wsdls/CreditoService.wsdl", endpointInterface = "br.com.soaexpert.creditoservice.CreditoService")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class CreditoService_CreditoServiceSOAPImpl implements CreditoService {

	private String[] cnpjs = {"11","22","33","44"};
	private Set<String> serasaRepo = new HashSet<String>();
	private Set<String> spcRepo = new HashSet<String>();
	private Set<String> bahiaRepo = new HashSet<String>();
	
	public CreditoService_CreditoServiceSOAPImpl(){
		serasaRepo.add(cnpjs[0]);
		spcRepo.add(cnpjs[0]);
		bahiaRepo.add(cnpjs[0]);
		
		serasaRepo.add(cnpjs[1]);
	}
	
	/**
	 * 
	 * @param empresa
	 * @return returns br.com.soaexpert.domain.Credito
	 */
	public Credito vefiricaCreditoSerasa(Empresa empresa) {
		Credito credito = new Credito();
		credito.setEmpresa(empresa);
		credito.setSerasa(new Random().nextBoolean());
		return credito;
	}

	/**
	 * 
	 * @param empresa
	 * @return returns br.com.soaexpert.domain.Credito
	 */
	public Credito verificaCreditoSPC(Empresa empresa) {
		Credito credito = new Credito();
		credito.setEmpresa(empresa);
		credito.setSpc(serasaRepo.contains(empresa.getCnpj()));
		return credito;
	}

	/**
	 * 
	 * @param empresa
	 * @return returns br.com.soaexpert.domain.Credito
	 */
	public Credito verificaCasasBahia(Empresa empresa) {
		Credito credito = new Credito();
		credito.setEmpresa(empresa);
		credito.setCasasBahia(new Random().nextBoolean());
		return credito;
	}

}
